export const getTeamAbbr = (teamName: string, sportKey: string): string => {
  console.log(sportKey)
  // Map full team names to abbreviations as used in your SVG filenames
  const mapNfl: Record<string, string> = {
    'Arizona Cardinals': 'ARI',
    'Atlanta Falcons': 'ATL',
    'Baltimore Ravens': 'BAL',
    'Buffalo Bills': 'BUF',
    'Carolina Panthers': 'CAR',
    'Chicago Bears': 'CHI',
    'Cincinnati Bengals': 'CIN',
    'Cleveland Browns': 'CLE',
    'Dallas Cowboys': 'DAL',
    'Denver Broncos': 'DEN',
    'Detroit Lions': 'DET',
    'Green Bay Packers': 'GB',
    'Houston Texans': 'HOU',
    'Indianapolis Colts': 'IND',
    'Jacksonville Jaguars': 'JAX',
    'Kansas City Chiefs': 'KC',
    'Las Vegas Raiders': 'LV',
    'Los Angeles Chargers': 'LAC',
    'Los Angeles Rams': 'LAR',
    'Miami Dolphins': 'MIA',
    'Minnesota Vikings': 'MIN',
    'New England Patriots': 'NE',
    'New Orleans Saints': 'NO',
    'New York Giants': 'NYG',
    'New York Jets': 'NYJ',
    'Philadelphia Eagles': 'PHI',
    'Pittsburgh Steelers': 'PIT',
    'San Francisco 49ers': 'SF',
    'Seattle Seahawks': 'SEA',
    'Tampa Bay Buccaneers': 'TB',
    'Tennessee Titans': 'TEN',
    'Washington Commanders': 'WAS',
    'Oakland Raiders': 'OAK',
    'San Diego Chargers': 'SD',
    'St. Louis Rams': 'STL',
    // Add any legacy/alternate names as needed
  };
  const mapNcaaf: Record<string, string> = {
    'Boston College Eagles': 'BC',
    'Clemson Tigers': 'CLEM',
    'Duke Blue Devils': 'DUKE',
    'Florida State Seminoles': 'FSU',
    'Georgia Tech Yellow Jackets': 'GT',
    'Louisville Cardinals': 'LOU',
    'Miami (FL) Hurricanes': 'MIA',
    'North Carolina Tar Heels': 'UNC',
    'NC State Wolfpack': 'NCST',
    'Pittsburgh Panthers': 'PITT',
    'Syracuse Orange': 'SYR',
    'Virginia Cavaliers': 'UVA',
    'Virginia Tech Hokies': 'VT',
    'Wake Forest Demon Deacons': 'WAKE',
    'California Golden Bears': 'CAL',
    'Stanford Cardinal': 'STAN',
    'SMU Mustangs': 'SMU',
    'Illinois Fighting Illini': 'ILL',
    'Indiana Hoosiers': 'IND',
    'Iowa Hawkeyes': 'IOWA',
    'Maryland Terrapins': 'MD',
    'Michigan Wolverines': 'MICH',
    'Michigan State Spartans': 'MSU',
    'Minnesota Golden Gophers': 'MINN',
    'Nebraska Cornhuskers': 'NEB',
    'Northwestern Wildcats': 'NW',
    'Ohio State Buckeyes': 'OHST',
    'Penn State Nittany Lions': 'PSU',
    'Purdue Boilermakers': 'PUR',
    'Rutgers Scarlet Knights': 'RUTG',
    'Wisconsin Badgers': 'WISC',
    'UCLA Bruins': 'UCLA',
    'USC Trojans': 'USC',
    'Oregon Ducks': 'ORE',
    'Washington Huskies': 'WASH',
    'Alabama Crimson Tide': 'ALA',
    'Arkansas Razorbacks': 'ARK',
    'Auburn Tigers': 'AUB',
    'Florida Gators': 'FLA',
    'Georgia Bulldogs': 'UGA',
    'Kentucky Wildcats': 'UK',
    'LSU Tigers': 'LSU',
    'Mississippi State Bulldogs': 'MSST',
    'Missouri Tigers': 'MIZZ',
    'Ole Miss Rebels': 'MISS',
    'South Carolina Gamecocks': 'SCAR',
    'Tennessee Volunteers': 'TENN',
    'Texas A&M Aggies': 'TAMU',
    'Vanderbilt Commodores': 'VAND',
    'Oklahoma Sooners': 'OKLA',
    'Texas Longhorns': 'TEX',
    'Arizona Wildcats': 'ARIZ',
    'Arizona State Sun Devils': 'ASU',
    'Baylor Bears': 'BAY',
    'BYU Cougars': 'BYU',
  // 'Cincinnati Bearcats': 'CINC', // Removed: no CINC.png in ncaaf folder
    'Colorado Buffaloes': 'COLO',
    'Houston Cougars': 'HOU',
    'Iowa State Cyclones': 'ISU',
    'Kansas Jayhawks': 'KU',
    'Kansas State Wildcats': 'KSU',
    'Oklahoma State Cowboys': 'OKST',
    'TCU Horned Frogs': 'TCU',
    'Texas Tech Red Raiders': 'TTU',
    'UCF Knights': 'UCF',
    'Utah Utes': 'UTAH',
    'West Virginia Mountaineers': 'WVU',
    'Oregon State Beavers': 'ORST',
    'Washington State Cougars': 'WSU',
    'Charlotte 49ers': 'CHAR',
    'East Carolina Pirates': 'ECU',
    'Florida Atlantic Owls': 'FAU',
    'Memphis Tigers': 'MEM',
    'Navy Midshipmen': 'NAVY',
    'North Texas Mean Green': 'UNT',
    'Rice Owls': 'RICE',
    'South Florida Bulls': 'USF',
    'Temple Owls': 'TEM',
    'Tulane Green Wave': 'TULN',
    'Tulsa Golden Hurricane': 'TLSA',
    'UAB Blazers': 'UAB',
    'UTSA Roadrunners': 'UTSA',
    'Army Black Knights': 'ARMY',
    'Appalachian State Mountaineers': 'APP',
    'Arkansas State Red Wolves': 'ARKST',
    'Coastal Carolina Chanticleers': 'CCU',
    'Georgia Southern Eagles': 'GASO',
    'Georgia State Panthers': 'GAST',
    'James Madison Dukes': 'JMU',
    'Louisiana Ragin\' Cajuns': 'LA',
    'Louisiana-Monroe Warhawks': 'ULM',
    'Marshall Thundering Herd': 'MRSH',
    'Old Dominion Monarchs': 'ODU',
    'South Alabama Jaguars': 'USA',
    'Southern Miss Golden Eagles': 'USM',
    'Texas State Bobcats': 'TXST',
    'Troy Trojans': 'TROY',
    'Air Force Falcons': 'AFA',
    'Boise State Broncos': 'BOISE',
    'Colorado State Rams': 'CSU',
    'Fresno State Bulldogs': 'FRES',
    'Hawaii Rainbow Warriors': 'HAW',
    'Nevada Wolf Pack': 'NEV',
    'New Mexico Lobos': 'UNM',
    'San Diego State Aztecs': 'SDSU',
    'San Jose State Spartans': 'SJSU',
    'UNLV Rebels': 'UNLV',
    'Utah State Aggies': 'USU',
    'Wyoming Cowboys': 'WYO',
    'Akron Zips': 'AKR',
    'Ball State Cardinals': 'BALL',
    'Bowling Green Falcons': 'BGSU',
    'Buffalo Bulls': 'BUFF',
    'Central Michigan Chippewas': 'CMU',
    'Eastern Michigan Eagles': 'EMU',
    'Kent State Golden Flashes': 'KENT',
    'Miami (OH) RedHawks': 'M-OH',
    'Northern Illinois Huskies': 'NIU',
    'Ohio Bobcats': 'OHIO',
    'Toledo Rockets': 'TOL',
    'Western Michigan Broncos': 'WMU',
    'FIU Panthers': 'FIU',
    'Jacksonville State Gamecocks': 'JSU',
    'Kennesaw State Owls': 'KENN',
    'Liberty Flames': 'LIB',
    'Louisiana Tech Bulldogs': 'LT',
    'Middle Tennessee Blue Raiders': 'MTSU',
    'New Mexico State Aggies': 'NMSU',
    'Sam Houston Bearkats': 'SHSU',
    'UTEP Miners': 'UTEP',
    'Western Kentucky Hilltoppers': 'WKU',
    'Notre Dame Fighting Irish': 'ND',
    'UConn Huskies': 'CONN',
    'UMass Minutemen': 'UMASS',
    'Miami Hurricanes': 'MIA',
    'Louisiana Ragin Cajuns': 'LA',
    'UL Lafayette Ragin\' Cajuns': 'LA',
    'Louisiana Lafayette Ragin\' Cajuns': 'LA',
    'Ole Miss Rebels (Mississippi)': 'MISS',
    'Pitt Panthers': 'PITT',
    'Cal Golden Bears': 'CAL',
    'South Carolina Gamecocks (SC)': 'SCAR',
  };
  if (sportKey === 'americanfootball_nfl') {
    return mapNfl[teamName] || 'default';
  } else if (sportKey === 'americanfootball_ncaaf') {
    return mapNcaaf[teamName] || 'default';
  } else {
    return 'default';
  }
}

