import { Injectable, signal } from '@angular/core';

@Injectable({ providedIn: 'root' })
export class SportService {
  sportKey = signal('americanfootball_ncaaf'); // default value

  setSportKey(key: string) {
    this.sportKey.set(key);
  }
}
// export const sportsKeys = [
//   "americanfootball_cfl",
//   "americanfootball_ncaaf",
//   "americanfootball_ncaaf_championship_winner",
//   "americanfootball_nfl",
//   "americanfootball_nfl_preseason",
//   "americanfootball_nfl_super_bowl_winner",
//   "americanfootball_ufl",

//   "aussierules_afl",

//   "baseball_mlb",
//   "baseball_mlb_preseason",
//   "baseball_mlb_world_series_winner",
//   "baseball_milb",
//   "baseball_npb",
//   "baseball_kbo",
//   "baseball_ncaa",

//   "basketball_euroleague",
//   "basketball_nba",
//   "basketball_nba_preseason",
//   "basketball_nba_summer_league",
//   "basketball_nba_championship_winner",
//   "basketball_wnba",
//   "basketball_ncaab",
//   "basketball_wncaab",
//   "basketball_ncaab_championship_winner",
//   "basketball_nbl",

//   "boxing_boxing",

//   "cricket_big_bash",
//   "cricket_caribbean_premier_league",
//   "cricket_icc_trophy",
//   "cricket_icc_world_cup",
//   "cricket_international_t20",
//   "cricket_ipl",
//   "cricket_odi",
//   "cricket_psl",
//   "cricket_t20_blast",
//   "cricket_test_match",
//   "cricket_the_hundred",

//   "golf_masters_tournament_winner",
//   "golf_pga_championship_winner",
//   "golf_the_open_championship_winner",
//   "golf_us_open_winner",

//   "icehockey_nhl",
//   "icehockey_ahl",
//   "icehockey_nhl_championship_winner",
//   "icehockey_liiga",
//   "icehockey_mestis",
//   "icehockey_sweden_hockey_league",
//   "icehockey_sweden_allsvenskan",

//   "lacrosse_pll",
//   "lacrosse_ncaa",

//   "mma_mixed_martial_arts",

//   "politics_us_presidential_election_winner",

//   "rugbyleague_nrl",
//   "rugbyleague_nrl_state_of_origin",

//   "rugbyunion_six_nations",

//   "soccer_africa_cup_of_nations",
//   "soccer_argentina_primera_division",
//   "soccer_australia_aleague",
//   "soccer_austria_bundesliga",
//   "soccer_belgium_first_div",
//   "soccer_brazil_campeonato",
//   "soccer_brazil_serie_b",
//   "soccer_chile_campeonato",
//   "soccer_china_superleague",
//   "soccer_denmark_superliga",
//   "soccer_efl_champ",
//   "soccer_england_efl_cup",
//   "soccer_england_league1",
//   "soccer_england_league2",
//   "soccer_epl",
//   "soccer_fa_cup",
//   "soccer_fifa_world_cup",
//   "soccer_fifa_world_cup_qualifiers_europe",
//   "soccer_fifa_world_cup_qualifiers_south_america",
//   "soccer_fifa_world_cup_womens",
//   "soccer_fifa_world_cup_winner",
//   "soccer_fifa_club_world_cup",
//   "soccer_finland_veikkausliiga",
//   "soccer_france_ligue_one",
//   "soccer_france_ligue_two",
//   "soccer_germany_bundesliga",
//   "soccer_germany_bundesliga2",
//   "soccer_germany_liga3",
//   "soccer_greece_super_league",
//   "soccer_italy_serie_a",
//   "soccer_italy_serie_b",
//   "soccer_japan_j_league",
//   "soccer_korea_kleague1",
//   "soccer_league_of_ireland",
//   "soccer_mexico_ligamx",
//   "soccer_netherlands_eredivisie",
//   "soccer_norway_eliteserien",
//   "soccer_poland_ekstraklasa",
//   "soccer_portugal_primeira_liga",
//   "soccer_spain_la_liga",
//   "soccer_spain_segunda_division",
//   "soccer_spl",
//   "soccer_sweden_allsvenskan",
//   "soccer_sweden_superettan",
//   "soccer_switzerland_superleague",
//   "soccer_turkey_super_league",
//   "soccer_uefa_europa_conference_league",
//   "soccer_uefa_champs_league",
//   "soccer_uefa_champs_league_qualification",
//   "soccer_uefa_europa_league",
//   "soccer_uefa_european_championship",
//   "soccer_uefa_euro_qualification",
//   "soccer_uefa_nations_league",
//   "soccer_concacaf_gold_cup",
//   "soccer_concacaf_leagues_cup",
//   "soccer_conmebol_copa_america",
//   "soccer_conmebol_copa_libertadores",
//   "soccer_conmebol_copa_sudamericana",
//   "soccer_usa_mls",

//   "tennis_atp_aus_open_singles",
//   "tennis_atp_canadian_open",
//   "tennis_atp_china_open",
//   "tennis_atp_cincinnati_open",
//   "tennis_atp_dubai",
//   "tennis_atp_french_open",
//   "tennis_atp_indian_wells",
//   "tennis_atp_italian_open",
//   "tennis_atp_madrid_open",
//   "tennis_atp_miami_open",
//   "tennis_atp_monte_carlo_masters",
//   "tennis_atp_paris_masters",
//   "tennis_atp_qatar_open",
//   "tennis_atp_shanghai_masters",
//   "tennis_atp_us_open",
//   "tennis_atp_wimbledon",

//   "tennis_wta_aus_open_singles",
//   "tennis_wta_canadian_open",
//   "tennis_wta_china_open",
//   "tennis_wta_cincinnati_open",
//   "tennis_wta_dubai",
//   "tennis_wta_french_open",
//   "tennis_wta_indian_wells",
//   "tennis_wta_italian_open",
//   "tennis_wta_madrid_open",
//   "tennis_wta_miami_open",
//   "tennis_wta_qatar_open",
//   "tennis_wta_us_open",
//   "tennis_wta_wimbledon",
//   "tennis_wta_wuhan_open"
// ] as const;
